server:
  port: 8087
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    password: root
    url: mysql://bed7dd0a0c866a:81c1d54b@us-cdbr-east-02.cleardb.com/heroku_e7fd44431ed4a51?reconnect=true
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
