DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE IF NOT EXISTS `CUSTOMER`
(
    `MOBILE_NUMBER` VARCHAR(20) NOT NULL PRIMARY KEY,
    `CUSTOMER_NAME` VARCHAR(20),
    `DUE_AMOUNT`    VARCHAR(20),
    `DUE_DATE`      VARCHAR(20),
    `REF_ID`        VARCHAR(200),
    `AMOUNT_PAID`   VARCHAR(20),
    `ACK_ID`        VARCHAR(200),
    `DATE`          VARCHAR(20)
);